// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/customers" | "/customers/[id]" | "/customers/new" | "/dashboard" | "/invoices" | "/invoices/[id]" | "/invoices/[id]/edit" | "/invoices/[id]/preview" | "/invoices/new" | "/login" | "/quotations" | "/quotations/[id]" | "/quotations/[id]/edit" | "/quotations/[id]/preview" | "/quotations/new" | "/receipts" | "/receipts/[id]" | "/receipts/[id]/preview" | "/register" | "/settings"
type AppRouteHandlerRoutes = "/api/documents/generate-pdf" | "/api/documents/whatsapp-log" | "/api/health/db" | "/api/invoices/[id]/generate-pdf" | "/api/invoices/[id]/generate-receipt" | "/api/quotations/[id]/convert-to-invoice"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/documents/generate-pdf": {}
  "/api/documents/whatsapp-log": {}
  "/api/health/db": {}
  "/api/invoices/[id]/generate-pdf": { "id": string; }
  "/api/invoices/[id]/generate-receipt": { "id": string; }
  "/api/quotations/[id]/convert-to-invoice": { "id": string; }
  "/customers": {}
  "/customers/[id]": { "id": string; }
  "/customers/new": {}
  "/dashboard": {}
  "/invoices": {}
  "/invoices/[id]": { "id": string; }
  "/invoices/[id]/edit": { "id": string; }
  "/invoices/[id]/preview": { "id": string; }
  "/invoices/new": {}
  "/login": {}
  "/quotations": {}
  "/quotations/[id]": { "id": string; }
  "/quotations/[id]/edit": { "id": string; }
  "/quotations/[id]/preview": { "id": string; }
  "/quotations/new": {}
  "/receipts": {}
  "/receipts/[id]": { "id": string; }
  "/receipts/[id]/preview": { "id": string; }
  "/register": {}
  "/settings": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
